image: Visual Studio 2019

configuration: Release
platform: x64

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - ps: .\before_build.ps1

build:
  parallel: true
  project: openssh-portable\contrib\win32\openssh\Win32-OpenSSH.sln


  artifacts:
    - path: openssh-portable